# nome da pipeline
name: Run Basic Testes

# em que momento será executada
on:
    pull_request:
        branches: [main]

jobs:
    # o que vai ser feito nessa pipeline
    #só teremos um job: que será rodar os teste
    cypress-run:
        # maquina que será executado
        runs-on: ubuntu-latest

        #passo a passo para rodar os teste
        steps:
            # clone do projeto
            - name: checkout do projeto
              uses: actions/checkout@v4

            #execução e configuração do projeto
            - name: Cypress run
              uses: cypress-io/github-action@v6
              with:
                start: npm start
                record: true
              env:
                CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}